### ISSUE TITLE
API Loading error

### ISSUE THREAD

**Issue by maryampashmi** [lavinjj/coding-smackdown-bbq-cook-log#1]
Hi,

I am trying to clone your repository after to years in order to work with  form following your video. I got several problem  which all related to dependency issues, well, after 2 years everything is being changed. I have tried to install last version of dependency related. However i got error with "https://api-content.dropbox.com/1/files/auto/bbq-cook-log.json?client_id=vmgj6yecetgfi6u"  which it is not possible to load it. I would like to ask you what i should do in order to run your code. 

In fact i am not able to see any things in UI.

Best,

**Comment by lavinjj** [comment]
This should now be fixed with the latest version. Seems that there were issues with using "latest" in the bower.json file causing issues with the install of files. Good luck.
